#!/bin/sh

# Đợi hệ thống sinh xong cấu hình network mặc định (nếu có)
[ -f /etc/config/network ] || exit 1

# 0. Xóa bỏ cấu hình IPv6 (wan6) để đảm bảo ổn định định tuyến và VPN
uci -q delete network.wan6

# 1. Cấu hình PPPoE cho WAN (Chỉ sửa proto, username, password)
uci set network.wan=interface
uci set network.wan.proto='pppoe'
uci set network.wan.device='eth1'
uci set network.wan.username='c710_gftth_tunt162'
uci set network.wan.password='O8WIYG'
uci set network.wan.ipv6='0'
uci set network.wan.mtu='1492'
uci set network.wan.peerdns='0'
uci add_list network.wan.dns='8.8.8.8'
uci add_list network.wan.dns='1.1.1.1'
uci set network.wan.dns_metric='100'
uci set network.wan.metric='100'
uci set network.wan.multipath='off'


# 2. Tạo Interface WireGuard một cách an toàn (Xóa cái cũ nếu trùng tên)
uci set network.sg=interface
uci set network.sg.proto='wireguard'
uci add network wireguard_sg
uci set network.@wireguard_sg[-1].description='Imported peer configuration'
uci set network.@wireguard_sg[-1].public_key='MGfgkhJsMVMTO33h1wr76+z6gQr/93VcGdClfbaPsnU='
uci add_list network.@wireguard_sg[-1].allowed_ips='0.0.0.0/0'
uci set network.@wireguard_sg[-1].endpoint_host='sg-sng.prod.surfshark.com'
uci set network.@wireguard_sg[-1].endpoint_port='51820'
uci set network.sg.private_key='SIMVtI2UGwIRNkStqfv5/9TKgqxlg3lkVH4aD6HoSWM='
uci add_list network.sg.addresses='10.14.0.2/16'
uci add_list network.sg.dns='162.252.172.57'
uci add_list network.sg.dns='149.154.159.92'
uci set network.sg.multipath='off'
uci set network.sg.dns_metric='50'
uci set network.sg.metric='50'
uci set network.@wireguard_sg[-1].route_allowed_ips='1'
uci set network.@wireguard_sg[-1].persistent_keepalive='25'


# 4. Thêm sg vào Firewall WAN một cách linh hoạt
cfg_find_wan_zone() {
    local cfg="$1"
    local name
    config_get name "$cfg" name
    if [ "$name" = "wan" ]; then
        uci add_list firewall."$cfg".network='sg'
    fi
}
. /lib/functions.sh
config_load firewall
config_foreach cfg_find_wan_zone zone

# --- CẤU HÌNH WI-FI ĐỘNG (BẬT 5G, THIẾT LẬP WPA3 THUẦN) ---

# Bắt hệ thống nhận diện phần cứng và sinh file cấu hình Wi-Fi
[ -f /etc/config/wireless ] || wifi config

. /lib/functions.sh
config_load wireless

change_wifi() {
    local config="$1"
    local device
    
    config_get device "$config" device

    local band
    config_get band "$device" band

    if [ "$band" = "2g" ]; then
        # Tắt phần cứng 2.4GHz
        uci set wireless."$device".disabled='1'
        
    elif [ "$band" = "5g" ]; then
        # Bật phần cứng 5GHz
        uci set wireless."$device".disabled='0'
        
        # Thiết lập tên
        uci set wireless."$config".ssid='DKM VIETTEL'
        
        # Thiết lập chuẩn WPA3-SAE (Không trộn lẫn)
        uci set wireless."$config".encryption='sae' 
        uci set wireless."$config".key='12344321'
        
        # BẮT BUỘC ĐỐI VỚI WPA3: Thiết lập PMF thành 2 (Required)
        uci set wireless."$config".ieee80211w='2'
    fi
}

# Quét tất cả các interface Wi-Fi và áp dụng logic trên
config_foreach change_wifi wifi-iface

# Lưu cấu hình và khởi động lại dịch vụ Wi-Fi
uci commit wireless



# Lưu toàn bộ cấu hình
uci commit network
uci commit firewall

# Khởi động lại dịch vụ để áp dụng ngay
/etc/init.d/network restart
/etc/init.d/firewall restart
wifi reload
# Xóa script để không chạy lại ở lần boot sau
rm -f /etc/uci-defaults/n60pro-custom-network
exit 0

